[build]
pipelining = false

[target.nvptx64-nvidia-cuda]
rustflags = ["-Clink-args=--arch=sm_35", "-Cpanic=abort", "-Clinker-plugin-lto", "-Ccodegen-units=1", "-Clink-arg=-Olto"]

[unstable]
build-std = ["core", "alloc"]
build-std-features = ["panic_immediate_abort"]
features = ["all"]
